### ISSUE TITLE
TypeError: mkdirp is not a function when call set method in electron production build app

### ISSUE THREAD

**Issue by JackZhang1988** [electron-userland/electron-json-storage#208]
When I'm using this package in dev mode, everything is fine, but when i build it with ```electron-builder``` and run the build app, every feature by using ```Storage.set``` is not working. In but app log, it shows below errors:

>**TypeError: mkdirp is not a function**
    at /Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/electron-json-storage/lib/storage.js:393:7
    at nextTask (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5791:13)
    at next (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5799:13)
    at /Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:329:20
    at /Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:167:17
    at /Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:59:23
    at nextTask (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5791:13)
    at Object.waterfall (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:5802:9)
    at Object.awaitable [as waterfall] (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/async/dist/async.js:212:32)
    at exports.set (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/node_modules/electron-json-storage/lib/storage.js:380:9)
    at IpcMainImpl.<anonymous> (/Users/zhangjianbo/Projects/Personal/apitune/apitune-app/dist/mac-arm64/ApiTune.app/Contents/Resources/app.asar/out/main/index.js:12838:17)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)

I'm not sure where the issue is, the 'mkdirp' package in successfully installed and it all works in dev mode, how could this issue happen in prod mode?

**Comment by JackZhang1988** [comment]
It seems like the ```mkdirp``` package version is conflicted with project's version, i remove my project's mkdirp and it works now.
